= Ensure that there's no coredump storage in /etc/systemd/coredump.conf

== Description

The `Storage` option controls where to store cores.  One of "none", "external",
and "journal". When "none", the core dumps may be logged (including the
backtrace if possible), but not stored permanently.

Setting `Storage=none` and `ProcessSizeMax=0` disables all coredump handling
except for a log entry.

== Rationale

Kernel core dumps may contain the full contents of system memory at the time of
the crash. Kernel core dumps may consume a considerable amount of disk space and
may result in denial of service by exhausting the available space on the target
file system partition.

== Audit

[source,shell]
----
@test "Ensure that there's no coredump storage in /etc/systemd/coredump.conf" {
  run bash -c "grep '^Storage=none$' /etc/systemd/coredump.conf"
  [ "$status" -eq 0 ]
}
----

== Remediation

=== shell

[source,shell]
----
sed -i 's/^#Storage=.*/Storage=none/' "/etc/systemd/coredump.conf"
----

== References

STIG-ID: UBTU-16-010900 +
STIG-ID: RHEL-07-021300 +
CIS RHEL 7 Benchmark 2.2.0: 1.5.1 +
CIS Ubuntu 18.04 v1.0.0: 1.5.1 +
https://www.freedesktop.org/software/systemd/man/coredump.conf.html[https://www.freedesktop.org/software/systemd/man/coredump.conf.html]
